export interface Company {
  symbol: string;
  name: string;
  sector: string;
}

export const COMPANIES: Company[] = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "IT" },
  { symbol: "INFY.NS", name: "Infosys", sector: "IT" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "FMCG" },
  { symbol: "ITC.NS", name: "ITC Limited", sector: "FMCG" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking" },
  { symbol: "LT.NS", name: "Larsen & Toubro", sector: "Infra" },
  { symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Banking" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Finance" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki", sector: "Auto" },
  { symbol: "WIPRO.NS", name: "Wipro", sector: "IT" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "IT" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Cement" },
  { symbol: "NESTLEIND.NS", name: "Nestle India", sector: "FMCG" },
  { symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical", sector: "Pharma" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories", sector: "Pharma" },
  { symbol: "TECHM.NS", name: "Tech Mahindra", sector: "IT" },
  { symbol: "SBIN.NS", name: "State Bank of India", sector: "Banking" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corp", sector: "Energy" },
  { symbol: "NTPC.NS", name: "NTPC Limited", sector: "Energy" },
  { symbol: "ONGC.NS", name: "ONGC", sector: "Energy" },
  { symbol: "COALINDIA.NS", name: "Coal India", sector: "Mining" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Metals" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Metals" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Finance" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Conglomerate" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports", sector: "Infra" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Auto" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Auto" },
  { symbol: "SHREECEM.NS", name: "Shree Cement", sector: "Cement" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories", sector: "Pharma" },
  { symbol: "CIPLA.NS", name: "Cipla", sector: "Pharma" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare" },
  { symbol: "BPCL.NS", name: "BPCL", sector: "Energy" },
  { symbol: "GRASIM.NS", name: "Grasim Industries", sector: "Manufacturing" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries", sector: "Metals" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank", sector: "Banking" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "FMCG" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries", sector: "FMCG" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance", sector: "Insurance" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance", sector: "Insurance" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Auto" },
  { symbol: "UPL.NS", name: "UPL Limited", sector: "Agro" },
  { symbol: "DMART.NS", name: "Avenue Supermarts", sector: "Retail" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Chemicals" },
  { symbol: "AAPL", name: "Apple Inc.", sector: "Tech" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Tech" },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Tech" },
  { symbol: "AMZN", name: "Amazon.com", sector: "E-commerce" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Chips" },
  { symbol: "META", name: "Meta Platforms", sector: "Social" },
  { symbol: "TSLA", name: "Tesla, Inc.", sector: "EV" },
  { symbol: "NFLX", name: "Netflix, Inc.", sector: "Streaming" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Chips" },
  { symbol: "INTC", name: "Intel Corporation", sector: "Chips" },
  { symbol: "SAMSUNG", name: "Samsung Electronics", sector: "Tech" },
];

export const SECTOR_COLORS: Record<string, string> = {
  IT: "#3B82F6",
  Banking: "#8B5CF6",
  Energy: "#F59E0B",
  FMCG: "#10B981",
  Auto: "#F97316",
  Finance: "#6366F1",
  Pharma: "#EC4899",
  Metals: "#6B7280",
  Telecom: "#14B8A6",
  Infra: "#84CC16",
  Consumer: "#F472B6",
  Cement: "#A78BFA",
  Mining: "#78716C",
  Insurance: "#22D3EE",
  Healthcare: "#34D399",
  Retail: "#FB923C",
  Tech: "#60A5FA",
  Chips: "#A855F7",
  "E-commerce": "#FBBF24",
  Social: "#38BDF8",
  EV: "#4ADE80",
  Streaming: "#F87171",
  Agro: "#86EFAC",
  Chemicals: "#FDE68A",
  Manufacturing: "#C4B5FD",
  Conglomerate: "#FCA5A5",
};
